<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rt</string>
	</array>
	<key>name</key>
	<string>React Templates</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.tag.tagbraces.django</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>storage.type.variable.django</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.rt</string>
	<key>uuid</key>
	<string>b9225a83-611a-4f0a-bd66-4180d3b6a21b</string>
</dict>
</plist>
